### ISSUE TITLE
[bug] actions でこける(arxiv の api)

### ISSUE THREAD

**Issue by fkubota** [fkubota/Carrier-Owl#73]
関連ci: https://github.com/fkubota/Carrier-Owl/runs/6331532347?check_suite_focus=true

**Comment by fkubota** [comment]
- [x] ローカルで動く？
  - 動く
- [ ] poetry でのバージョン一致してる？

**Comment by ryamaguchi0111** [comment]
質問です．
このバグはもう解決とかできるのでしょうか？

**Comment by fkubota** [comment]
@ryamaguchi0111   
こちらのリリースで解決しています！  
https://github.com/fkubota/Carrier-Owl/releases/tag/v2.1.3

**Comment by fkubota** [comment]
このPRで修正済み  
https://github.com/fkubota/Carrier-Owl/pull/75

**Comment by ryamaguchi0111** [comment]
@fkubota 
こちらと似たようなバグが発生しているのですが原因わかりますか？
以下，エラーメッセージ
```
Run poetry run python src/carrier_owl.py
[WDM] - ====== WebDriver manager ======
[WDM] - There is no [linux64] geckodriver for browser  in cache
[WDM] - Getting latest mozilla release info for v0.31.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/runner/.wdm/drivers/geckodriver/linux64/v0.31.0]


Traceback (most recent call last):
  File "src/carrier_owl.py", line 189, in <module>
    main()
  File "src/carrier_owl.py", line 181, in main
    results = search_keyword(articles, keywords, score_threshold)
  File "src/carrier_owl.py", line 60, in search_keyword
    title_trans = get_translated_text('ja', 'en', title, driver)
  File "src/carrier_owl.py", line [13](https://github.com/ryamaguchi0111/Carrier-Owl/runs/7670223058?check_suite_focus=true#step:6:14)6, in get_translated_text
    to_text = get_text_from_page_source(html)
  File "src/carrier_owl.py", line [14](https://github.com/ryamaguchi0111/Carrier-Owl/runs/7670223058?check_suite_focus=true#step:6:15)6, in get_text_from_page_source
    text = target_elem.text
AttributeError: 'NoneType' object has no attribute 'text'
Error: Process completed with exit code 1.
```

**Comment by fkubota** [comment]
@ryamaguchi0111 
先程、こちらのPRによって修正しました。   
最新のmasterは動作するようになっています。
https://github.com/fkubota/Carrier-Owl/pull/83
